services:
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017

  typesense:
    image: typesense/typesense:0.25.2
    ports:
      - 8108:8108
    restart: on-failure
    volumes:
      - ./typesense-data:/data
    environment:
      - TYPESENSE_ENABLE_CORS=true
    command: '--data-dir /data --api-key=xyz --enable-cors'

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - 5173:5173
