[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["wordsea"]

[project]
name = "wordsea"
version = "0.0.0"
dependencies = [
    "accelerate",
    "beautifulsoup4",
    "diffusers",
    "pandas",
    "peft",
    "sentencepiece",
    "tqdm",
    "torch",
    "transformers",
]
requires-python = ">=3.10"
description = "Expand your vocabulary with wordsea!"

[project.scripts]
wordsea = "wordsea:main"
wordsea-clean = "wordsea.scripts.clean:main"
